
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 05 20:40:03 EEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 44;
  public static final int GREATER_OR_EQUAL = 24;
  public static final int PRINT_KEYWORD = 41;
  public static final int UMINUS = 21;
  public static final int NOT_EQUAL = 27;
  public static final int LPAREN = 12;
  public static final int RBRAC = 11;
  public static final int MINUS = 20;
  public static final int GREATER_THAN = 23;
  public static final int RPAREN = 13;
  public static final int CHARACTER_LITERAL = 45;
  public static final int NOT = 9;
  public static final int SEMICOLON = 16;
  public static final int AND = 6;
  public static final int LESS_OR_EQUAL = 25;
  public static final int OR = 7;
  public static final int NEW_KEYWORD = 38;
  public static final int PLUS = 19;
  public static final int ASSIGN = 4;
  public static final int EOF = 0;
  public static final int EQUAL = 26;
  public static final int MISSING_KEYWORD = 3;
  public static final int error = 1;
  public static final int COMA = 5;
  public static final int LCURLY = 14;
  public static final int MOD = 8;
  public static final int RCURLY = 15;
  public static final int TIMES = 17;
  public static final int FLOAT_KEYWORD = 29;
  public static final int RETURN_KEYWORD = 35;
  public static final int WHILE_KEYWORD = 31;
  public static final int DELETE_KEYWORD = 39;
  public static final int INT_KEYWORD = 28;
  public static final int STRING_KEYWORD = 34;
  public static final int LBRAC = 10;
  public static final int CONTINUE_KEYWORD = 37;
  public static final int FLOAT_LITERAL = 43;
  public static final int CHAR_KEYWORD = 30;
  public static final int DIVISION = 18;
  public static final int VOID_KEYWORD = 40;
  public static final int LESS_THAN = 22;
  public static final int IF_KEYWORD = 32;
  public static final int ELSE_KEYWORD = 33;
  public static final int INTEGER_LITERAL = 42;
  public static final int BREAK_KEYWORD = 36;
  public static final int IDENTIFIER = 2;
}

