
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 20 17:56:20 EEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 12;
  public static final int SEMICOLON = 10;
  public static final int PLUS = 14;
  public static final int RPAREN = 7;
  public static final int EQUAL = 21;
  public static final int GREATER_THAN = 18;
  public static final int WHILE = 4;
  public static final int DIVISION = 13;
  public static final int RCURLY = 9;
  public static final int IDENTIFIER = 2;
  public static final int NOT_EQUAL = 22;
  public static final int LPAREN = 6;
  public static final int STRING_LITERAL = 25;
  public static final int DO = 5;
  public static final int LCURLY = 8;
  public static final int EOF = 0;
  public static final int LESS_THAN = 17;
  public static final int MINUS = 15;
  public static final int LESS_OR_EQUAL = 20;
  public static final int PRINT = 3;
  public static final int error = 1;
  public static final int EQ = 11;
  public static final int INTEGER_LITERAL = 23;
  public static final int GREATER_OR_EQUAL = 19;
  public static final int DOUBLE_LITERAL = 24;
  public static final int UMINUS = 16;
}

